channels:
  - conda-forge
dependencies:
  - git
  - jupyter
  - matplotlib
  - nbgitpuller
  - numpy
  - orange3
  - pandas
  - pip
  - python
  - scikit-learn
  - seaborn
  - setuptools
  - pip:
    - geopandas
    - nbconvert[webpdf]
